package io.anthonylombardo321.github.mtatracker;

import java.util.HashMap;

public class SubwayMap {

    public SubwayMap(){
    }

    public HashMap<String, String[]> getSubwayStationServices(){
        HashMap<String, String[]> services_in_subway_stations = new HashMap<>();
        services_in_subway_stations.put("First Avenue", new String[]{"L"});
        services_in_subway_stations.put("Second Avenue", new String[]{"F"});
        services_in_subway_stations.put("Third Avenue", new String[]{"L"});
        services_in_subway_stations.put("Third Avenue–138th Street", new String[]{"6"});
        services_in_subway_stations.put("Third Avenue–149th Street", new String[]{"2", "5"});
        services_in_subway_stations.put("Fourth Avenue/Ninth Street", new String[]{"R", "F", "G"});
        services_in_subway_stations.put("Fifth Avenue", new String[]{"7"});
        services_in_subway_stations.put("Fifth Avenue/53rd Street", new String[]{"E", "M"});
        services_in_subway_stations.put("Fifth Avenue–59th Street", new String[]{"N", "R", "W"});
        services_in_subway_stations.put("Sixth Avenue", new String[]{"L"});
        services_in_subway_stations.put("Seventh Avenue", new String[]{"B", "D", "E", "F", "G", "Q"});
        services_in_subway_stations.put("Eighth Avenue", new String[]{"N", "L"});
        services_in_subway_stations.put("Eighth Street–New York University", new String[]{"R", "W"});
        services_in_subway_stations.put("Ninth Avenue", new String[]{"D"});
        services_in_subway_stations.put("14th Street", new String[]{"F", "M", "1", "2", "3", "A", "C", "E"});
        services_in_subway_stations.put("14th Street–Union Square", new String[]{"N", "Q", "R", "W", "L", "4", "5", "6"});
        services_in_subway_stations.put("15th Street–Prospect Park", new String[]{"F", "G"});
        services_in_subway_stations.put("18th Avenue", new String[]{"F", "N", "D"});
        services_in_subway_stations.put("18th Street", new String[]{"1"});
        services_in_subway_stations.put("20th Avenue", new String[]{"N", "D"});
        services_in_subway_stations.put("21st Street", new String[]{"G"});
        services_in_subway_stations.put("21st Street–Queensbridge", new String[]{"F"});
        services_in_subway_stations.put("23rd Street", new String[]{"F", "M", "C", "E", "R", "W", "6"});
        services_in_subway_stations.put("25th Avenue", new String[]{"D"});
        services_in_subway_stations.put("25th Street", new String[]{"R"});
        services_in_subway_stations.put("28th Street", new String[]{"R", "W", "1", "6"});
        services_in_subway_stations.put("30th Avenue", new String[]{"N", "W"});
        services_in_subway_stations.put("33rd Street", new String[]{"6"});
        services_in_subway_stations.put("33rd Street–Rawson Street", new String[]{"7"});
        services_in_subway_stations.put("34th Street–Herald Square", new String[]{"B", "D", "F", "M", "N", "Q", "R", "W"});
        services_in_subway_stations.put("34th Street–Hudson Yards", new String[]{"7"});
        services_in_subway_stations.put("34th Street–Penn Station", new String[]{"A", "C", "E", "1", "2", "3"});
        services_in_subway_stations.put("36th Avenue", new String[]{"N", "W"});
        services_in_subway_stations.put("36th Street", new String[]{"D", "N", "M", "R"});
        services_in_subway_stations.put("39th Avenue", new String[]{"N", "W"});
        services_in_subway_stations.put("40th Street–Lowery Street", new String[]{"7"});
        services_in_subway_stations.put("42nd Street–Bryant Park", new String[]{"B", "D", "F", "M"});
        services_in_subway_stations.put("42nd Street–Port Authority Bus Terminal", new String[]{"A", "C", "E"});
        services_in_subway_stations.put("45th Street", new String[]{"R"});
        services_in_subway_stations.put("46th Street", new String[]{"M", "R"});
        services_in_subway_stations.put("46th Street–Bliss Street", new String[]{"7"});
        services_in_subway_stations.put("47th–50th Streets–Rockefeller Center", new String[]{"B", "D", "F", "M"});
        services_in_subway_stations.put("49th Street", new String[]{"N", "R", "W"});
        services_in_subway_stations.put("50th Street", new String[]{"C", "E", "1", "D"});
        services_in_subway_stations.put("51st Street", new String[]{"6"});
        services_in_subway_stations.put("52nd Street", new String[]{"7"});
        services_in_subway_stations.put("53rd Street", new String[]{"R"});
        services_in_subway_stations.put("55th Street", new String[]{"D"});
        services_in_subway_stations.put("57th Street", new String[]{"F"});
        services_in_subway_stations.put("57th Street–Seventh Avenue", new String[]{"N", "Q", "R", "W"});
        services_in_subway_stations.put("59th Street", new String[]{"4", "5", "6", "N", "R"});
        services_in_subway_stations.put("59th Street–Columbus Circle", new String[]{"A", "B", "C", "D", "1"});
        services_in_subway_stations.put("61st Street–Woodside", new String[]{"7"});
        services_in_subway_stations.put("62nd Street", new String[]{"D"});
        services_in_subway_stations.put("63rd Drive–Rego Park", new String[]{"M", "R"});
        services_in_subway_stations.put("65th Street", new String[]{"M", "R"});
        services_in_subway_stations.put("66th Street–Lincoln Center", new String[]{"1"});
        services_in_subway_stations.put("67th Avenue", new String[]{"M", "R"});
        services_in_subway_stations.put("68th Street–Hunter College", new String[]{"6"});
        services_in_subway_stations.put("69th Street", new String[]{"7"});
        services_in_subway_stations.put("71st Street", new String[]{"D"});
        services_in_subway_stations.put("72nd Street", new String[]{"Q", "B", "C", "1", "2", "3"});
        services_in_subway_stations.put("74th Street–Broadway", new String[]{"7"});
        services_in_subway_stations.put("75th Avenue", new String[]{"F"});
        services_in_subway_stations.put("75th Street–Elderts Lane", new String[]{"J"});
        services_in_subway_stations.put("77th Street", new String[]{"R", "6"});
        services_in_subway_stations.put("79th Street", new String[]{"1", "D"});
        services_in_subway_stations.put("80th Street", new String[]{"A"});
        services_in_subway_stations.put("81st Street–Museum of Natural History", new String[]{"B", "C"});
        services_in_subway_stations.put("82nd Street–Jackson Heights", new String[]{"7"});
        services_in_subway_stations.put("85th Street–Forest Parkway", new String[]{"J"});
        services_in_subway_stations.put("86th Street", new String[]{"Q", "R", "B", "C", "1", "4", "5", "6", "N"});
        services_in_subway_stations.put("88th Street", new String[]{"A"});
        services_in_subway_stations.put("90th Street–Elmhurst Avenue", new String[]{"7"});
        services_in_subway_stations.put("96th Street", new String[]{"1", "2", "3", "6", "B", "C", "Q"});
        services_in_subway_stations.put("103rd Street", new String[]{"1", "6", "B", "C"});
        services_in_subway_stations.put("103rd Street–Corona Plaza", new String[]{"7"});
        services_in_subway_stations.put("104th Street", new String[]{"A", "J"});
        services_in_subway_stations.put("110th Street", new String[]{"6"});
        services_in_subway_stations.put("111th Street", new String[]{"7", "A", "J"});
        services_in_subway_stations.put("116th Street", new String[]{"2", "3", "6", "B", "C"});
        services_in_subway_stations.put("116th Street–Columbia University", new String[]{"1"});
        services_in_subway_stations.put("121st Street", new String[]{"J"});
        services_in_subway_stations.put("125th Street", new String[]{"1", "2", "3", "4", "5", "6", "A", "B", "C", "D"});
        services_in_subway_stations.put("135th Street", new String[]{"2", "3", "B", "C"});
        services_in_subway_stations.put("137th Street–City College", new String[]{"1"});
        services_in_subway_stations.put("138th Street–Grand Concourse", new String[]{"4", "5"});
        services_in_subway_stations.put("145th Street", new String[]{"1", "3", "A", "B", "C", "D"});
        services_in_subway_stations.put("149th Street–Grand Concourse", new String[]{"2", "4", "5"});
        services_in_subway_stations.put("155th Street", new String[]{"C", "D"});
        services_in_subway_stations.put("157th Street", new String[]{"1"});
        services_in_subway_stations.put("161st Street–Yankee Stadium", new String[]{"4", "D"});
        services_in_subway_stations.put("163rd Street–Amsterdam Avenue", new String[]{"C"});
        services_in_subway_stations.put("167th Street", new String[]{"4", "D"});
        services_in_subway_stations.put("168th Street", new String[]{"A", "C"});
        services_in_subway_stations.put("168th Street–Washington Heights", new String[]{"1"});
        services_in_subway_stations.put("169th Street", new String[]{"F"});
        services_in_subway_stations.put("170th Street", new String[]{"4", "D"});
        services_in_subway_stations.put("174th Street", new String[]{"2", "5"});
        services_in_subway_stations.put("174th–175th Streets", new String[]{"D"});
        services_in_subway_stations.put("175th Street", new String[]{"A"});
        services_in_subway_stations.put("176th Street", new String[]{"4"});
        services_in_subway_stations.put("181st Street", new String[]{"1", "A"});
        services_in_subway_stations.put("182nd–183rd Streets", new String[]{"D"});
        services_in_subway_stations.put("183rd Street", new String[]{"4"});
        services_in_subway_stations.put("190th Street", new String[]{"A"});
        services_in_subway_stations.put("191st Street", new String[]{"1"});
        services_in_subway_stations.put("207th Street", new String[]{"1"});
        services_in_subway_stations.put("215th Street", new String[]{"1"});
        services_in_subway_stations.put("219th Street", new String[]{"2"});
        services_in_subway_stations.put("225th Street", new String[]{"2"});
        services_in_subway_stations.put("231st Street", new String[]{"1"});
        services_in_subway_stations.put("233rd Street", new String[]{"2"});
        services_in_subway_stations.put("238th Street", new String[]{"1"});
        services_in_subway_stations.put("Alabama Avenue", new String[]{"J"});
        services_in_subway_stations.put("Allerton Avenue", new String[]{"2"});
        services_in_subway_stations.put("Aqueduct Racetrack", new String[]{"A"});
        services_in_subway_stations.put("Aqueduct–North Conduit Avenue", new String[]{"A"});
        services_in_subway_stations.put("Astor Place", new String[]{"6"});
        services_in_subway_stations.put("Astoria Boulevard", new String[]{"N", "W"});
        services_in_subway_stations.put("Astoria–Ditmars Boulevard", new String[]{"N", "W"});
        services_in_subway_stations.put("Atlantic Avenue", new String[]{"L"});
        services_in_subway_stations.put("Atlantic Avenue–Barclays Center", new String[]{"D", "N", "R", "B", "Q", "2", "3", "4", "5"});
        services_in_subway_stations.put("Avenue H", new String[]{"Q"});
        services_in_subway_stations.put("Avenue I", new String[]{"F"});
        services_in_subway_stations.put("Avenue J", new String[]{"Q"});
        services_in_subway_stations.put("Avenue M", new String[]{"Q"});
        services_in_subway_stations.put("Avenue N", new String[]{"F"});
        services_in_subway_stations.put("Avenue P", new String[]{"F"});
        services_in_subway_stations.put("Avenue U", new String[]{"F", "N", "Q"});
        services_in_subway_stations.put("Avenue X", new String[]{"F"});
        services_in_subway_stations.put("Bay 50th Street", new String[]{"D"});
        services_in_subway_stations.put("Bay Parkway", new String[]{"D", "F", "N"});
        services_in_subway_stations.put("Bay Ridge Avenue", new String[]{"R"});
        services_in_subway_stations.put("Bay Ridge–95th Street", new String[]{"R"});
        services_in_subway_stations.put("Baychester Avenue", new String[]{"5"});
        services_in_subway_stations.put("Beach 25th Street", new String[]{"A"});
        services_in_subway_stations.put("Beach 36th Street", new String[]{"A"});
        services_in_subway_stations.put("Beach 44th Street", new String[]{"A"});
        services_in_subway_stations.put("Beach 60th Street", new String[]{"A"});
        services_in_subway_stations.put("Beach 67th Street", new String[]{"A"});
        services_in_subway_stations.put("Beach 90th Street", new String[]{"Rockaway Park Shuttle"});
        services_in_subway_stations.put("Beach 98th Street", new String[]{"Rockaway Park Shuttle"});
        services_in_subway_stations.put("Beach 105th Street", new String[]{"Rockaway Park Shuttle"});
        services_in_subway_stations.put("Bedford Avenue", new String[]{"L"});
        services_in_subway_stations.put("Bedford Park Boulevard", new String[]{"D"});
        services_in_subway_stations.put("Bedford Park Boulevard–Lehman College", new String[]{"4"});
        services_in_subway_stations.put("Bedford–Nostrand Avenues", new String[]{"G"});
        services_in_subway_stations.put("Bergen Street", new String[]{"2", "3", "F", "G"});
        services_in_subway_stations.put("Beverley Road", new String[]{"Q"});
        services_in_subway_stations.put("Beverly Road", new String[]{"2", "5"});
        services_in_subway_stations.put("Bleecker Street", new String[]{"6"});
        services_in_subway_stations.put("Borough Hall", new String[]{"2", "3", "4", "5"});
        services_in_subway_stations.put("Botanic Garden", new String[]{"Franklin Avenue Shuttle"});
        services_in_subway_stations.put("Bowery", new String[]{"J"});
        services_in_subway_stations.put("Bowling Green", new String[]{"4", "5"});
        services_in_subway_stations.put("Briarwood", new String[]{"F"});
        services_in_subway_stations.put("Brighton Beach", new String[]{"B", "Q"});
        services_in_subway_stations.put("Broad Channel", new String[]{"A", "Rockaway Park Shuttle"});
        services_in_subway_stations.put("Broad Street", new String[]{"J"});
        services_in_subway_stations.put("Broadway", new String[]{"N", "W", "G"});
        services_in_subway_stations.put("Broadway Junction", new String[]{"L", "A", "C", "J"});
        services_in_subway_stations.put("Broadway–Lafayette Street", new String[]{"B", "D", "F", "M"});
        services_in_subway_stations.put("Bronx Park East", new String[]{"2"});
        services_in_subway_stations.put("Brook Avenue", new String[]{"6"});
        services_in_subway_stations.put("Brooklyn Bridge–City Hall", new String[]{"4", "5", "6"});
        services_in_subway_stations.put("Buhre Avenue", new String[]{"6"});
        services_in_subway_stations.put("Burke Avenue", new String[]{"2"});
        services_in_subway_stations.put("Burnside Avenue", new String[]{"4"});
        services_in_subway_stations.put("Bushwick Avenue–Aberdeen Street", new String[]{"L"});
        services_in_subway_stations.put("Canal Street", new String[]{"1", "6", "A", "C", "E", "J", "N", "Q", "R", "W"});
        services_in_subway_stations.put("Canarsie–Rockaway Parkway", new String[]{"L"});
        services_in_subway_stations.put("Castle Hill Avenue", new String[]{"6"});
        services_in_subway_stations.put("Cathedral Parkway–110th Street", new String[]{"1", "B", "C"});
        services_in_subway_stations.put("Carroll Street", new String[]{"F", "G"});
        services_in_subway_stations.put("Central Avenue", new String[]{"M"});
        services_in_subway_stations.put("Central Park North–110th Street", new String[]{"2", "3"});
        services_in_subway_stations.put("Chambers Street", new String[]{"1", "2", "3", "A", "C", "J"});
        services_in_subway_stations.put("Chauncey Street", new String[]{"J"});
        services_in_subway_stations.put("Christopher Street–Sheridan Square", new String[]{"1"});
        services_in_subway_stations.put("Church Avenue", new String[]{"2", "5", "B", "F", "G", "Q"});
        services_in_subway_stations.put("City Hall", new String[]{"R", "W"});
        services_in_subway_stations.put("Clark Street", new String[]{"2", "3"});
        services_in_subway_stations.put("Classon Avenue", new String[]{"G"});
        services_in_subway_stations.put("Cleveland Street", new String[]{"J"});
        services_in_subway_stations.put("Clinton–Washington Avenues", new String[]{"C", "G"});
        services_in_subway_stations.put("Coney Island–Stillwell Avenue", new String[]{"D", "F", "N", "Q"});
        services_in_subway_stations.put("Cortelyou Road", new String[]{"Q"});
        services_in_subway_stations.put("Cortlandt Street", new String[]{"R", "W"});
        services_in_subway_stations.put("Court Square", new String[]{"G", "7"});
        services_in_subway_stations.put("Court Square–23rd Street", new String[]{"E", "M"});
        services_in_subway_stations.put("Court Street", new String[]{"R"});
        services_in_subway_stations.put("Crescent Street", new String[]{"J"});
        services_in_subway_stations.put("Crown Heights–Utica Avenue", new String[]{"3", "4"});
        services_in_subway_stations.put("Cypress Avenue", new String[]{"6"});
        services_in_subway_stations.put("Cypress Hills", new String[]{"J"});
        services_in_subway_stations.put("DeKalb Avenue", new String[]{"B", "L", "Q", "R"});
        services_in_subway_stations.put("Delancey Street/Essex Street", new String[]{"F", "J", "M"});
        services_in_subway_stations.put("Ditmas Avenue", new String[]{"F"});
        services_in_subway_stations.put("Dyckman Street", new String[]{"1", "A"});
        services_in_subway_stations.put("East 105th Street", new String[]{"L"});
        services_in_subway_stations.put("East 143rd Street–St. Mary's Street", new String[]{"6"});
        services_in_subway_stations.put("East 149th Street", new String[]{"6"});
        services_in_subway_stations.put("East 180th Street", new String[]{"2", "5"});
        services_in_subway_stations.put("East Broadway", new String[]{"F"});
        services_in_subway_stations.put("Eastchester–Dyre Avenue", new String[]{"5"});
        services_in_subway_stations.put("Eastern Parkway–Brooklyn Museum", new String[]{"2", "3"});
        services_in_subway_stations.put("Elder Avenue", new String[]{"6"});
        services_in_subway_stations.put("Elmhurst Avenue", new String[]{"M", "R"});
        services_in_subway_stations.put("Euclid Avenue", new String[]{"A", "C"});
        services_in_subway_stations.put("Far Rockaway–Mott Avenue", new String[]{"A"});
        services_in_subway_stations.put("Flatbush Avenue–Brooklyn College", new String[]{"2", "5"});
        services_in_subway_stations.put("Flushing Avenue", new String[]{"G", "J", "M"});
        services_in_subway_stations.put("Flushing–Main Street", new String[]{"7"});
        services_in_subway_stations.put("Fordham Road", new String[]{"4", "D"});
        services_in_subway_stations.put("Forest Avenue", new String[]{"M"});
        services_in_subway_stations.put("Forest Hills–71st Avenue", new String[]{"E", "F", "M", "R"});
        services_in_subway_stations.put("Fort Hamilton Parkway", new String[]{"D", "F", "G", "N"});
        services_in_subway_stations.put("Franklin Avenue", new String[]{"Franklin Avenue Shuttle", "C"});
        services_in_subway_stations.put("Franklin Avenue–Medgar Evers College", new String[]{"2", "3", "4", "5"});
        services_in_subway_stations.put("Franklin Street", new String[]{"1"});
        services_in_subway_stations.put("Freeman Street", new String[]{"2", "5"});
        services_in_subway_stations.put("Fresh Pond Road", new String[]{"M"});
        services_in_subway_stations.put("Fulton Street", new String[]{"2", "3", "4", "5", "A", "C", "J", "G"});
        services_in_subway_stations.put("Gates Avenue", new String[]{"J"});
        services_in_subway_stations.put("Graham Avenue", new String[]{"L"});
        services_in_subway_stations.put("Grand Army Plaza", new String[]{"2", "3"});
        services_in_subway_stations.put("Grand Avenue–Newtown", new String[]{"M", "R"});
        services_in_subway_stations.put("Grand Central–42nd Street", new String[]{"42nd Street Shuttle", "7", "4", "5", "6"});
        services_in_subway_stations.put("Grand Street", new String[]{"B", "D", "L"});
        services_in_subway_stations.put("Grant Avenue", new String[]{"A"});
        services_in_subway_stations.put("Greenpoint Avenue", new String[]{"G"});
        services_in_subway_stations.put("Gun Hill Road", new String[]{"2", "5"});
        services_in_subway_stations.put("Halsey Street", new String[]{"L", "J"});
        services_in_subway_stations.put("Harlem–148th Street", new String[]{"3"});
        services_in_subway_stations.put("Hewes Street", new String[]{"J", "M"});
        services_in_subway_stations.put("High Street", new String[]{"A", "C"});
        services_in_subway_stations.put("Houston Street", new String[]{"1"});
        services_in_subway_stations.put("Howard Beach–JFK Airport", new String[]{"A"});
        services_in_subway_stations.put("Hoyt Street", new String[]{"2", "3"});
        services_in_subway_stations.put("Hoyt–Schermerhorn Streets", new String[]{"A", "C", "G"});
        services_in_subway_stations.put("Hunters Point Avenue", new String[]{"7"});
        services_in_subway_stations.put("Hunts Point Avenue", new String[]{"6"});
        services_in_subway_stations.put("Intervale Avenue", new String[]{"2", "5"});
        services_in_subway_stations.put("Inwood–207th Street", new String[]{"A"});
        services_in_subway_stations.put("Jackson Avenue", new String[]{"2", "5"});
        services_in_subway_stations.put("Jackson Heights–Roosevelt Avenue", new String[]{"E", "F", "M", "R"});
        services_in_subway_stations.put("Jamaica Center–Parsons/Archer", new String[]{"E", "J"});
        services_in_subway_stations.put("Jamaica–179th Street", new String[]{"F"});
        services_in_subway_stations.put("Jamaica–Van Wyck", new String[]{"E"});
        services_in_subway_stations.put("Jay Street–MetroTech", new String[]{"R", "A", "C", "F"});
        services_in_subway_stations.put("Jefferson Street", new String[]{"L"});
        services_in_subway_stations.put("Junction Boulevard", new String[]{"7"});
        services_in_subway_stations.put("Junius Street", new String[]{"3"});
        services_in_subway_stations.put("Kew Gardens–Union Turnpike", new String[]{"E", "F"});
        services_in_subway_stations.put("Kings Highway", new String[]{"B", "F", "N", "Q"});
        services_in_subway_stations.put("Kingsbridge Road", new String[]{"4", "D"});
        services_in_subway_stations.put("Kingston Avenue", new String[]{"3"});
        services_in_subway_stations.put("Kingston–Throop Avenues", new String[]{"C"});
        services_in_subway_stations.put("Knickerbocker Avenue", new String[]{"M"});
        services_in_subway_stations.put("Kosciuszko Street", new String[]{"J"});
        services_in_subway_stations.put("Lafayette Avenue", new String[]{"C"});
        services_in_subway_stations.put("Lexington Avenue–53rd Street", new String[]{"E", "M"});
        services_in_subway_stations.put("Lexington Avenue–59th Street", new String[]{"N", "R", "W"});
        services_in_subway_stations.put("Lexington Avenue–63rd Street", new String[]{"F", "Q"});
        services_in_subway_stations.put("Liberty Avenue", new String[]{"C"});
        services_in_subway_stations.put("Livonia Avenue", new String[]{"L"});
        services_in_subway_stations.put("Longwood Avenue", new String[]{"6"});
        services_in_subway_stations.put("Lorimer Street", new String[]{"J", "L", "M"});
        services_in_subway_stations.put("Marble Hill–225th Street", new String[]{"1"});
        services_in_subway_stations.put("Marcy Avenue", new String[]{"J", "M"});
        services_in_subway_stations.put("Metropolitan Avenue", new String[]{"G"});
        services_in_subway_stations.put("Mets–Willets Point", new String[]{"7"});
        services_in_subway_stations.put("Middle Village–Metropolitan Avenue", new String[]{"M"});
        services_in_subway_stations.put("Middletown Road", new String[]{"6"});
        services_in_subway_stations.put("Montrose Avenue", new String[]{"L"});
        services_in_subway_stations.put("Morgan Avenue", new String[]{"L"});
        services_in_subway_stations.put("Morris Park", new String[]{"5"});
        services_in_subway_stations.put("Morrison Avenue–Soundview", new String[]{"6"});
        services_in_subway_stations.put("Mosholu Parkway", new String[]{"4"});
        services_in_subway_stations.put("Mount Eden Avenue", new String[]{"4"});
        services_in_subway_stations.put("Myrtle Avenue", new String[]{"J", "M"});
        services_in_subway_stations.put("Myrtle–Willoughby Avenues", new String[]{"G"});
        services_in_subway_stations.put("Myrtle–Wyckoff Avenues", new String[]{"L", "M"});
        services_in_subway_stations.put("Nassau Avenue", new String[]{"G"});
        services_in_subway_stations.put("Neck Road", new String[]{"Q"});
        services_in_subway_stations.put("Neptune Avenue", new String[]{"F"});
        services_in_subway_stations.put("Nereid Avenue", new String[]{"2"});
        services_in_subway_stations.put("Nevins Street", new String[]{"2", "3", "4", "5"});
        services_in_subway_stations.put("New Lots Avenue", new String[]{"3", "L"});
        services_in_subway_stations.put("New Utrecht Avenue", new String[]{"N"});
        services_in_subway_stations.put("Newkirk Avenue–Little Haiti", new String[]{"2", "5"});
        services_in_subway_stations.put("Newkirk Plaza", new String[]{"B", "Q"});
        services_in_subway_stations.put("Northern Boulevard", new String[]{"M", "R"});
        services_in_subway_stations.put("Norwood Avenue", new String[]{"J"});
        services_in_subway_stations.put("Norwood–205th Street", new String[]{"D"});
        services_in_subway_stations.put("Nostrand Avenue", new String[]{"3", "A", "C"});
        services_in_subway_stations.put("Ocean Parkway", new String[]{"Q"});
        services_in_subway_stations.put("Ozone Park–Lefferts Boulevard", new String[]{"A"});
        services_in_subway_stations.put("Park Place", new String[]{"2", "3", "Franklin Avenue Shuttle"});
        services_in_subway_stations.put("Parkchester", new String[]{"6"});
        services_in_subway_stations.put("Parkside Avenue", new String[]{"Q"});
        services_in_subway_stations.put("Parsons Boulevard", new String[]{"F"});
        services_in_subway_stations.put("Pelham Bay Park", new String[]{"6"});
        services_in_subway_stations.put("Pelham Parkway", new String[]{"2", "5"});
        services_in_subway_stations.put("Pennsylvania Avenue", new String[]{"3"});
        services_in_subway_stations.put("President Street–Medgar Evers College", new String[]{"2", "5"});
        services_in_subway_stations.put("Prince Street", new String[]{"R", "W"});
        services_in_subway_stations.put("Prospect Avenue", new String[]{"2", "5"});
        services_in_subway_stations.put("Prospect Park", new String[]{"B", "Q", "Franklin Avenue Shuttle"});
        services_in_subway_stations.put("Queens Plaza", new String[]{"E", "M", "R"});
        services_in_subway_stations.put("Queensboro Plaza", new String[]{"7", "N", "W"});
        services_in_subway_stations.put("Ralph Avenue", new String[]{"C"});
        services_in_subway_stations.put("Rector Street", new String[]{"1", "R", "W"});
        services_in_subway_stations.put("Rockaway Avenue", new String[]{"3", "C"});
        services_in_subway_stations.put("Rockaway Boulevard", new String[]{"A"});
        services_in_subway_stations.put("Rockaway Park–Beach 116th Street", new String[]{"Rockaway Park Shuttle"});
        services_in_subway_stations.put("Roosevelt Island", new String[]{"F"});
        services_in_subway_stations.put("Saratoga Avenue", new String[]{"3"});
        services_in_subway_stations.put("Seneca Avenue", new String[]{"M"});
        services_in_subway_stations.put("Sheepshead Bay", new String[]{"B", "Q"});
        services_in_subway_stations.put("Shepherd Avenue", new String[]{"C"});
        services_in_subway_stations.put("Simpson Street", new String[]{"2", "5"});
        services_in_subway_stations.put("Smith–Ninth Streets", new String[]{"F", "G"});
        services_in_subway_stations.put("South Ferry", new String[]{"1"});
        services_in_subway_stations.put("Spring Street", new String[]{"6"});
        services_in_subway_stations.put("St. Lawrence Avenue", new String[]{"6"});
        services_in_subway_stations.put("Steinway Street", new String[]{"M", "R"});
        services_in_subway_stations.put("Sterling Street", new String[]{"2", "5"});
        services_in_subway_stations.put("Sutphin Boulevard", new String[]{"F"});
        services_in_subway_stations.put("Sutphin Boulevard–Archer Avenue–JFK Airport", new String[]{"E", "J"});
        services_in_subway_stations.put("Sutter Avenue", new String[]{"L"});
        services_in_subway_stations.put("Sutter Avenue–Rutland Road", new String[]{"3"});
        services_in_subway_stations.put("Times Square–42nd Street", new String[]{"N", "Q", "R", "W", "1", "2", "3", "7", "42nd Street Shuttle"});
        services_in_subway_stations.put("Tremont Avenue", new String[]{"D"});
        services_in_subway_stations.put("Union Street", new String[]{"R"});
        services_in_subway_stations.put("Utica Avenue", new String[]{"A", "C"});
        services_in_subway_stations.put("Van Cortlandt Park–242nd Street", new String[]{"1"});
        services_in_subway_stations.put("Van Siclen Avenue", new String[]{"3", "C", "J"});
        services_in_subway_stations.put("Vernon Boulevard–Jackson Avenue", new String[]{"7"});
        services_in_subway_stations.put("Wakefield–241st Street", new String[]{"2"});
        services_in_subway_stations.put("Wall Street", new String[]{"2","3", "4", "5"});
        services_in_subway_stations.put("West Fourth Street–Washington Square", new String[]{"A", "B", "C", "D", "E", "F", "M"});
        services_in_subway_stations.put("West Eighth Street–New York Aquarium", new String[]{"F", "Q"});
        services_in_subway_stations.put("West Farms Square–East Tremont Avenue", new String[]{"2", "5"});
        services_in_subway_stations.put("Westchester Square–East Tremont Avenue", new String[]{"6"});
        services_in_subway_stations.put("Whitlock Avenue", new String[]{"6"});
        services_in_subway_stations.put("Whitehall Street–South Ferry", new String[]{"R", "W"});
        services_in_subway_stations.put("Wilson Avenue", new String[]{"L"});
        services_in_subway_stations.put("Winthrop Street", new String[]{"2", "5"});
        services_in_subway_stations.put("Woodhaven Boulevard", new String[]{"J", "M", "R"});
        services_in_subway_stations.put("Woodlawn", new String[]{"4"});
        services_in_subway_stations.put("World Trade Center", new String[]{"E"});
        services_in_subway_stations.put("WTC Cortlandt", new String[]{"1"});
        services_in_subway_stations.put("York Street", new String[]{"F"});
        services_in_subway_stations.put("Zerega Avenue", new String[]{"6"});
        return services_in_subway_stations;
    }

    public HashMap<String, String[]> getSubwayServiceStops(){
        HashMap<String, String[]> subway_services_last_stops = new HashMap<>();
        subway_services_last_stops.put("1", new String[]{"Van Cortlandt Park–242nd Street", "South Ferry"});
        subway_services_last_stops.put("2", new String[]{"Wakefield–241st Street", "Flatbush Avenue"});
        subway_services_last_stops.put("3", new String[]{"Harlem–148th Street", "New Lots Avenue"});
        subway_services_last_stops.put("4", new String[]{"Woodlawn", "Crown Heights–Utica Avenue"});
        subway_services_last_stops.put("5", new String[]{"Dyre Avenue", "Flatbush Avenue"});
        subway_services_last_stops.put("6", new String[]{"Pelham Bay Park", "Brooklyn Bridge–City Hall"});
        subway_services_last_stops.put("7", new String[]{"34th Street–Hudson Yards", "Flushing–Main Street"});
        subway_services_last_stops.put("A", new String[]{"Inwood–207th Street", "Lefferts Boulevard"});
        subway_services_last_stops.put("B", new String[]{"145th Street", "Brighton Beach"});
        subway_services_last_stops.put("C", new String[]{"168th Street", "Euclid Avenue"});
        subway_services_last_stops.put("D", new String[]{"Norwood–205th Street", "Coney Island–Stillwell Avenue"});
        subway_services_last_stops.put("E", new String[]{"World Trade Center", "Jamaica Center–Parsons/Archer"});
        subway_services_last_stops.put("F", new String[]{"Jamaica–179th Street", "Coney Island–Stillwell Avenue"});
        subway_services_last_stops.put("G", new String[]{"Court Square", "Church Avenue"});
        subway_services_last_stops.put("J", new String[]{"Jamaica Center–Parsons/Archer", "Broad Street"});
        subway_services_last_stops.put("L", new String[]{"Eighth Avenue", "Rockaway Parkway"});
        subway_services_last_stops.put("M", new String[]{"Forest Hills–71st Avenue", "Middle Village–Metropolitan Avenue"});
        subway_services_last_stops.put("N", new String[]{"Astoria–Ditmars Boulevard", "Coney Island–Stillwell Avenue"});
        subway_services_last_stops.put("Q", new String[]{"96th Street", "Coney Island–Stillwell Avenue"});
        subway_services_last_stops.put("R", new String[]{"Forest Hills–71st Avenue", "Bay Ridge–95th Street"});
        subway_services_last_stops.put("W", new String[]{"Astoria–Ditmars Boulevard", "Whitehall Street–South Ferry"});
        subway_services_last_stops.put("42nd Street Shuttle", new String[]{"Times Square", "Grand Central"});
        subway_services_last_stops.put("Franklin Avenue Shuttle", new String[]{"Franklin Avenue", "Prospect Park"});
        subway_services_last_stops.put("Rockaway Park Shuttle", new String[]{"Broad Channel", "Rockaway Park–Beach 116th Street"});
        return subway_services_last_stops;
    }

    public HashMap<String, String> getSubwayAPIHashMap(){
        HashMap<String, String> subwayHashMap = new HashMap<>();
        subwayHashMap.put("First Avenue", "1 Av");
        subwayHashMap.put("Second Avenue", "2 Av");
        subwayHashMap.put("Third Avenue", "3 Av");
        subwayHashMap.put("Third Avenue–138th Street", "3 Av-138 St");
        subwayHashMap.put("Third Avenue–149th Street", "3 Av-149 St");
        subwayHashMap.put("Fourth Avenue/Ninth Street", "4 Av-9 St");
        subwayHashMap.put("Fifth Avenue", "5 Av");
        subwayHashMap.put("Fifth Avenue/53rd Street", "5 Av/53 St");
        subwayHashMap.put("Fifth Avenue–59th Street", "5 Av/59 St");
        subwayHashMap.put("Sixth Avenue", "6 Av");
        subwayHashMap.put("Seventh Avenue", "7 Av");
        subwayHashMap.put("Eighth Avenue", "8 Av");
        subwayHashMap.put("Eighth Street–New York University", "8 St-NYU");
        subwayHashMap.put("Ninth Avenue", "9 Av");
        subwayHashMap.put("14th Street", "14 St");
        subwayHashMap.put("14th Street–Union Square", "14 St-Union Sq");
        subwayHashMap.put("15th Street–Prospect Park", "15 St-Prospect Park");
        subwayHashMap.put("18th Avenue", "18 Av");
        subwayHashMap.put("18th Street", "18 St");
        subwayHashMap.put("20th Avenue", "20 Av");
        subwayHashMap.put("21st Street", "21 St");
        subwayHashMap.put("21st Street–Queensbridge", "21 St-Queensbridge");
        subwayHashMap.put("23rd Street", "23 St");
        subwayHashMap.put("25th Avenue", "25 Av");
        subwayHashMap.put("25th Street", "25 St");
        subwayHashMap.put("28th Street", "28 St");
        subwayHashMap.put("30th Avenue", "30 Av");
        subwayHashMap.put("33rd Street", "33 St");
        subwayHashMap.put("33rd Street–Rawson Street", "33 St-Rawson St");
        subwayHashMap.put("34th Street–Herald Square", "34 St-Herald Sq");
        subwayHashMap.put("34th Street–Hudson Yards", "34 St-Hudson Yards");
        subwayHashMap.put("34th Street–Penn Station", "34 St-Penn Station");
        subwayHashMap.put("36th Avenue", "36 Av");
        subwayHashMap.put("36th Street", "36 St");
        subwayHashMap.put("39th Avenue", "39 Av-Dutch Kills");
        subwayHashMap.put("40th Street–Lowery Street", "40 St-Lowery St");
        subwayHashMap.put("42nd Street–Bryant Park", "42 St-Bryant Pk");
        subwayHashMap.put("42nd Street–Port Authority Bus Terminal", "42 St-Port Authority Bus Terminal");
        subwayHashMap.put("45th Street", "45 St");
        subwayHashMap.put("46th Street", "46 St");
        subwayHashMap.put("46th Street–Bliss Street", "46 St-Bliss St");
        subwayHashMap.put("47th–50th Streets–Rockefeller Center", "47-50 Sts-Rockefeller Ctr");
        subwayHashMap.put("49th Street", "49 St");
        subwayHashMap.put("50th Street", "50 St");
        subwayHashMap.put("51st Street", "51 St");
        subwayHashMap.put("52nd Street", "52 St");
        subwayHashMap.put("53rd Street", "53 St");
        subwayHashMap.put("55th Street", "55 St");
        subwayHashMap.put("57th Street", "57 St");
        subwayHashMap.put("57th Street–Seventh Avenue", "57 St-7 Av");
        subwayHashMap.put("59th Street", "59 St");
        subwayHashMap.put("59th Street–Columbus Circle", "59 St-Columbus Circle");
        subwayHashMap.put("61st Street–Woodside", "61 St-Woodside");
        subwayHashMap.put("62nd Street", "62 St");
        subwayHashMap.put("63rd Drive–Rego Park", "63 Dr-Rego Park");
        subwayHashMap.put("65th Street", "65 St");
        subwayHashMap.put("66th Street–Lincoln Center", "66 St-Lincoln Center");
        subwayHashMap.put("67th Avenue", "67 Av");
        subwayHashMap.put("68th Street–Hunter College", "68 St-Hunter College");
        subwayHashMap.put("69th Street", "69 St");
        subwayHashMap.put("71st Street", "71 St");
        subwayHashMap.put("72nd Street", "72 St");
        subwayHashMap.put("74th Street–Broadway", "74 St-Broadway");
        subwayHashMap.put("75th Avenue", "75 Av");
        subwayHashMap.put("75th Street–Elderts Lane", "75 St-Elderts Ln");
        subwayHashMap.put("77th Street", "77 St");
        subwayHashMap.put("79th Street", "79 St");
        subwayHashMap.put("80th Street", "80 St");
        subwayHashMap.put("81st Street–Museum of Natural History", "81 St-Museum of Natural History");
        subwayHashMap.put("82nd Street–Jackson Heights", "82 St-Jackson Hts");
        subwayHashMap.put("85th Street–Forest Parkway", "85 St-Forest Pkwy");
        subwayHashMap.put("86th Street", "86 St");
        subwayHashMap.put("88th Street", "88 St");
        subwayHashMap.put("90th Street–Elmhurst Avenue", "90 St-Elmhurst Av");
        subwayHashMap.put("96th Street", "96 St");
        subwayHashMap.put("103rd Street", "103 St");
        subwayHashMap.put("103rd Street–Corona Plaza", "103 St-Corona Plaza");
        subwayHashMap.put("104th Street", "104 St");
        subwayHashMap.put("110th Street", "110 St");
        subwayHashMap.put("111th Street", "111 St");
        subwayHashMap.put("116th Street", "116 St");
        subwayHashMap.put("116th Street–Columbia University", "116 St-Columbia University");
        subwayHashMap.put("121st Street", "121 St");
        subwayHashMap.put("125th Street", "125 St");
        subwayHashMap.put("135th Street", "135 St");
        subwayHashMap.put("137th Street–City College", "137 St-City College");
        subwayHashMap.put("138th Street–Grand Concourse", "138 St-Grand Concourse");
        subwayHashMap.put("145th Street", "145St");
        subwayHashMap.put("149th Street–Grand Concourse", "149 St-Grand Concourse");
        subwayHashMap.put("155th Street", "155 St");
        subwayHashMap.put("157th Street", "157 St");
        subwayHashMap.put("161st Street–Yankee Stadium", "161 St-Yankee Stadium");
        subwayHashMap.put("163rd Street–Amsterdam Avenue", "163 St-Amsterdam Av");
        subwayHashMap.put("167th Street", "167 St");
        subwayHashMap.put("168th Street", "168 St");
        subwayHashMap.put("168th Street–Washington Heights", "168 St-Washington Hts");
        subwayHashMap.put("169th Street", "169 St");
        subwayHashMap.put("170th Street", "170 St");
        subwayHashMap.put("174th Street", "174 St");
        subwayHashMap.put("174th–175th Streets", "174-175 Sts");
        subwayHashMap.put("175th Street", "175 St");
        subwayHashMap.put("176th Street", "176 St");
        subwayHashMap.put("181st Street", "181 St");
        subwayHashMap.put("182nd–183rd Streets", "182-183 Sts");
        subwayHashMap.put("183rd Street", "183 St");
        subwayHashMap.put("190th Street", "190 St");
        subwayHashMap.put("191st Street", "191 St");
        subwayHashMap.put("207th Street", "207 St");
        subwayHashMap.put("215th Street", "215 St");
        subwayHashMap.put("219th Street", "219 St");
        subwayHashMap.put("225th Street", "225 St");
        subwayHashMap.put("231st Street", "231 St");
        subwayHashMap.put("233rd Street", "233 St");
        subwayHashMap.put("238th Street", "238 St");
        subwayHashMap.put("Alabama Avenue", "Alabama Av");
        subwayHashMap.put("Allerton Avenue", "Allerton Av");
        subwayHashMap.put("Aqueduct Racetrack", "Aqueduct Racetrack");
        subwayHashMap.put("Aqueduct–North Conduit Avenue", "Aqueduct-N Conduit Av");
        subwayHashMap.put("Astor Place", "Astor Pl");
        subwayHashMap.put("Astoria Boulevard", "Astoria Blvd");
        subwayHashMap.put("Astoria–Ditmars Boulevard", "Astoria-Ditmars Blvd");
        subwayHashMap.put("Atlantic Avenue", "Atlantic Av");
        subwayHashMap.put("Atlantic Avenue–Barclays Center", "Atlantic Av-Barclays Ctr");
        subwayHashMap.put("Avenue H", "Avenue H");
        subwayHashMap.put("Avenue I", "Avenue I");
        subwayHashMap.put("Avenue J", "Avenue J");
        subwayHashMap.put("Avenue M", "Avenue M");
        subwayHashMap.put("Avenue N", "Avenue N");
        subwayHashMap.put("Avenue P", "Avenue P");
        subwayHashMap.put("Avenue U", "Avenue U");
        subwayHashMap.put("Avenue X", "Avenue X");
        subwayHashMap.put("Bay 50th Street", "Bay 50 St");
        subwayHashMap.put("Bay Parkway", "Bay Pkwy");
        subwayHashMap.put("Bay Ridge Avenue", "Bay Ridge Av");
        subwayHashMap.put("Bay Ridge–95th Street", "Bay Ridge-95 St");
        subwayHashMap.put("Baychester Avenue", "Baychester Av");
        subwayHashMap.put("Beach 25th Street", "Beach 25 St");
        subwayHashMap.put("Beach 36th Street", "Beach 36 St");
        subwayHashMap.put("Beach 44th Street", "Beach 44 St");
        subwayHashMap.put("Beach 60th Street", "Beach 60 St");
        subwayHashMap.put("Beach 67th Street", "Beach 67 St");
        subwayHashMap.put("Beach 90th Street", "Beach 90 St");
        subwayHashMap.put("Beach 98th Street", "Beach 98 St");
        subwayHashMap.put("Beach 105th Street", "Beach 105 St");
        subwayHashMap.put("Bedford Avenue", "Bedford Av");
        subwayHashMap.put("Bedford Park Boulevard", "Bedford Park Blvd");
        subwayHashMap.put("Bedford Park Boulevard–Lehman College", "Bedford Park Blvd-Lehman College");
        subwayHashMap.put("Bedford–Nostrand Avenues", "Bedford-Nostrand Avs");
        subwayHashMap.put("Bergen Street", "Bergen St");
        subwayHashMap.put("Beverley Road", "Beverley Rd");
        subwayHashMap.put("Beverly Road", "Beverly Rd");
        subwayHashMap.put("Bleecker Street", "Bleecker St");
        subwayHashMap.put("Borough Hall", "Borough Hall");
        subwayHashMap.put("Botanic Garden", "Botanic Garden");
        subwayHashMap.put("Bowery", "Bowery");
        subwayHashMap.put("Bowling Green", "Bowling Green");
        subwayHashMap.put("Briarwood", "Briarwood");
        subwayHashMap.put("Brighton Beach", "Brighton Beach");
        subwayHashMap.put("Broad Channel", "Broad Channel");
        subwayHashMap.put("Broad Street", "Broad St");
        subwayHashMap.put("Broadway", "Broadway");
        subwayHashMap.put("Broadway Junction", "Broadway Junction");
        subwayHashMap.put("Broadway–Lafayette Street", "Broadway-Lafayette St");
        subwayHashMap.put("Bronx Park East", "Bronx Park East");
        subwayHashMap.put("Brook Avenue", "Brook Av");
        subwayHashMap.put("Brooklyn Bridge–City Hall", "Brooklyn Bridge-City Hall");
        subwayHashMap.put("Buhre Avenue", "Buhre Av");
        subwayHashMap.put("Burke Avenue", "Burke Av");
        subwayHashMap.put("Burnside Avenue", "Burnside Av");
        subwayHashMap.put("Bushwick Avenue–Aberdeen Street", "Bushwick Av-Aberdeen St");
        subwayHashMap.put("Canal Street", "Canal St");
        subwayHashMap.put("Canarsie–Rockaway Parkway", "Canarsie-Rockaway Pkwy");
        subwayHashMap.put("Carroll Street", "Carroll St");
        subwayHashMap.put("Castle Hill Avenue", "Castle Hill Av");
        subwayHashMap.put("Cathedral Parkway–110th Street", "Cathedral Pkwy (110 St)");
        subwayHashMap.put("Central Avenue", "Central Av");
        subwayHashMap.put("Central Park North–110th Street", "Central Park North (110 St)");
        subwayHashMap.put("Chambers Street", "Chambers St");
        subwayHashMap.put("Chauncey Street", "Chauncey St");
        subwayHashMap.put("Christopher Street–Sheridan Square", "Christopher St-Sheridan Sq");
        subwayHashMap.put("Church Avenue", "Church Av");
        subwayHashMap.put("City Hall", "City Hall");
        subwayHashMap.put("Clark Street", "Clark St");
        subwayHashMap.put("Classon Avenue", "Classon Av");
        subwayHashMap.put("Cleveland Street", "Cleveland St");
        subwayHashMap.put("Clinton–Washington Avenues", "Clinton-Washington Avs");
        subwayHashMap.put("Coney Island–Stillwell Avenue", "Coney Island-Stillwell Av");
        subwayHashMap.put("Cortelyou Road", "Cortelyou Rd");
        subwayHashMap.put("Cortlandt Street", "Cortlandt St");
        subwayHashMap.put("Court Square", "Court Sq");
        subwayHashMap.put("Court Square–23rd Street", "Court Sq-23 St");
        subwayHashMap.put("Court Street", "Court St");
        subwayHashMap.put("Crescent Street", "Crescent St");
        subwayHashMap.put("Crown Heights–Utica Avenue", "Crown Hts-Utica Av");
        subwayHashMap.put("Cypress Avenue", "Cypress Av");
        subwayHashMap.put("Cypress Hills", "Cypress Hills");
        subwayHashMap.put("DeKalb Avenue", "DeKalb Av");
        subwayHashMap.put("Delancey Street/Essex Street", "Delancey St-Essex St");
        subwayHashMap.put("Ditmas Avenue", "Ditmas Av");
        subwayHashMap.put("Dyckman Street", "Dyckman St");
        subwayHashMap.put("East 105th Street", "East 105 St");
        subwayHashMap.put("East 143rd Street–St. Mary's Street", "E 143 St-St Mary's St");
        subwayHashMap.put("East 149th Street", "E 149 St");
        subwayHashMap.put("East 180th Street", "E 180 St");
        subwayHashMap.put("East Broadway", "East Broadway");
        subwayHashMap.put("Eastchester–Dyre Avenue", "Eastchester-Dyre Av");
        subwayHashMap.put("Eastern Parkway–Brooklyn Museum", "Eastern Pkwy-Brooklyn Museum");
        subwayHashMap.put("Elder Avenue", "Elder Av");
        subwayHashMap.put("Elmhurst Avenue", "Elmhurst Av");
        subwayHashMap.put("Euclid Avenue", "Euclid Av");
        subwayHashMap.put("Far Rockaway–Mott Avenue", "Far Rockaway-Mott Av");
        subwayHashMap.put("Flatbush Avenue–Brooklyn College", "Flatbush Av-Brooklyn College");
        subwayHashMap.put("Flushing Avenue", "Flushing Av");
        subwayHashMap.put("Flushing–Main Street", "Flushing-Main St");
        subwayHashMap.put("Fordham Road", "Fordham Rd");
        subwayHashMap.put("Forest Avenue", "Forest Av");
        subwayHashMap.put("Forest Hills–71st Avenue", "Forest Hills-71 Av");
        subwayHashMap.put("Fort Hamilton Parkway", "Fort Hamilton Pkwy");
        subwayHashMap.put("Franklin Avenue", "Franklin Av");
        subwayHashMap.put("Franklin Avenue–Medgar Evers College", "Franklin Av-Medgar Evers College");
        subwayHashMap.put("Franklin Street", "Franklin St");
        subwayHashMap.put("Freeman Street", "Freeman St");
        subwayHashMap.put("Fresh Pond Road", "Fresh Pond Rd");
        subwayHashMap.put("Fulton Street", "Fulton St");
        subwayHashMap.put("Gates Avenue", "Gates Av");
        subwayHashMap.put("Graham Avenue", "Graham Av");
        subwayHashMap.put("Grand Army Plaza", "Grand Army Plaza");
        subwayHashMap.put("Grand Avenue–Newtown", "Grand Av-Newtown");
        subwayHashMap.put("Grand Central–42nd Street", "Grand Central-42 St");
        subwayHashMap.put("Grand Street", "Grand St");
        subwayHashMap.put("Grant Avenue", "Grant Av");
        subwayHashMap.put("Greenpoint Avenue", "Greenpoint Av");
        subwayHashMap.put("Gun Hill Road", "Gun Hill Rd");
        subwayHashMap.put("Halsey Street", "Halsey St");
        subwayHashMap.put("Harlem–148th Street", "Harlem-148 St");
        subwayHashMap.put("Hewes Street", "Hewes St");
        subwayHashMap.put("High Street", "High St");
        subwayHashMap.put("Houston Street", "Houston St");
        subwayHashMap.put("Howard Beach–JFK Airport", "Howard Beach-JFK Airport");
        subwayHashMap.put("Hoyt Street", "Hoyt St");
        subwayHashMap.put("Hoyt–Schermerhorn Streets", "Hoyt-Schermerhorn Sts");
        subwayHashMap.put("Hunters Point Avenue", "Hunters Point Av");
        subwayHashMap.put("Hunts Point Avenue", "Hunts Point Av");
        subwayHashMap.put("Intervale Avenue", "Intervale Av");
        subwayHashMap.put("Inwood–207th Street", "Inwood-207 St");
        subwayHashMap.put("Jackson Avenue", "Jackson Av");
        subwayHashMap.put("Jackson Heights–Roosevelt Avenue", "Jackson Hts-Roosevelt Av");
        subwayHashMap.put("Jamaica Center–Parsons/Archer", "Jamaica Center-Parsons/Archer");
        subwayHashMap.put("Jamaica–179th Street", "Jamaica-179 St");
        subwayHashMap.put("Jamaica–Van Wyck", "Jamaica-Van Wyck");
        subwayHashMap.put("Jay Street–MetroTech", "Jay St-MetroTech");
        subwayHashMap.put("Jefferson Street", "Jefferson St");
        subwayHashMap.put("Junction Boulevard", "Junction Blvd");
        subwayHashMap.put("Junius Street", "Junius St");
        subwayHashMap.put("Kew Gardens–Union Turnpike", "Kew Gardens-Union Tpke");
        subwayHashMap.put("Kings Highway", "Kings Hwy");
        subwayHashMap.put("Kingsbridge Road", "Kingsbridge Rd");
        subwayHashMap.put("Kingston Avenue", "Kingston Av");
        subwayHashMap.put("Kingston–Throop Avenues", "Kingston-Throop Avs");
        subwayHashMap.put("Knickerbocker Avenue", "Knickerbocker Av");
        subwayHashMap.put("Kosciuszko Street", "Kosciuszko St");
        subwayHashMap.put("Lafayette Avenue", "Lafayette Av");
        subwayHashMap.put("Lexington Avenue–53rd Street", "Lexington Av/53 St");
        subwayHashMap.put("Lexington Avenue–59th Street", "Lexington Av/59 St");
        subwayHashMap.put("Lexington Avenue–63rd Street", "Lexington Av/63 St");
        subwayHashMap.put("Liberty Avenue", "Liberty Av");
        subwayHashMap.put("Livonia Avenue", "Livonia Av");
        subwayHashMap.put("Longwood Avenue", "Longwood Av");
        subwayHashMap.put("Lorimer Street", "Lorimer St");
        subwayHashMap.put("Marble Hill–225th Street", "Marble Hill-225 St");
        subwayHashMap.put("Marcy Avenue", "Marcy Av");
        subwayHashMap.put("Metropolitan Avenue", "Metropolitan Av");
        subwayHashMap.put("Mets–Willets Point", "Mets-Willets Point");
        subwayHashMap.put("Middle Village–Metropolitan Avenue", "Middle Village-Metropolitan Av");
        subwayHashMap.put("Middletown Road", "Middletown Rd");
        subwayHashMap.put("Montrose Avenue", "Montrose Av");
        subwayHashMap.put("Morgan Avenue", "Morgan Av");
        subwayHashMap.put("Morris Park", "Morris Park");
        subwayHashMap.put("Morrison Avenue–Soundview", "Morrison Av-Soundview");
        subwayHashMap.put("Mosholu Parkway", "Mosholu Pkwy");
        subwayHashMap.put("Mount Eden Avenue", "Mt Eden Av");
        subwayHashMap.put("Myrtle Avenue", "Myrtle Av");
        subwayHashMap.put("Myrtle–Willoughby Avenues", "Myrtle-Willoughby Avs");
        subwayHashMap.put("Myrtle–Wyckoff Avenues", "Myrtle-Wyckoff Avs");
        subwayHashMap.put("Nassau Avenue", "Nassau Av");
        subwayHashMap.put("Neck Road", "Neck Rd");
        subwayHashMap.put("Neptune Avenue", "Neptune Av");
        subwayHashMap.put("Nereid Avenue", "Nereid Av");
        subwayHashMap.put("Nevins Street", "Nevins St");
        subwayHashMap.put("New Lots Avenue", "New Lots Av");
        subwayHashMap.put("New Utrecht Avenue", "New Utrecht Av");
        subwayHashMap.put("Newkirk Avenue–Little Haiti", "Newkirk Av-Little Haiti");
        subwayHashMap.put("Newkirk Plaza", "Newkirk Plaza");
        subwayHashMap.put("Northern Boulevard", "Northern Blvd");
        subwayHashMap.put("Norwood Avenue", "Norwood Av");
        subwayHashMap.put("Norwood–205th Street", "Norwood-205 St");
        subwayHashMap.put("Nostrand Avenue", "Nostrand Av");
        subwayHashMap.put("Ocean Parkway", "Ocean Pkwy");
        subwayHashMap.put("Ozone Park–Lefferts Boulevard", "Ozone Park-Lefferts Blvd");
        subwayHashMap.put("Park Place", "Park Place");
        subwayHashMap.put("Parkchester", "Parkchester");
        subwayHashMap.put("Parkside Avenue", "Parkside Av");
        subwayHashMap.put("Parsons Boulevard", "Parsons Blvd");
        subwayHashMap.put("Pelham Bay Park", "Pelham Bay Park");
        subwayHashMap.put("Pelham Parkway", "Pelham Pkwy");
        subwayHashMap.put("Pennsylvania Avenue", "Pennsylvania Av");
        subwayHashMap.put("President Street–Medgar Evers College", "President St-Medgar Evers College");
        subwayHashMap.put("Prince Street", "Prince St");
        subwayHashMap.put("Prospect Avenue", "Prospect Av");
        subwayHashMap.put("Prospect Park", "Prospect Park");
        subwayHashMap.put("Queensboro Plaza", "Queensboro Plaza");
        subwayHashMap.put("Queens Plaza", "Queens Plaza");
        subwayHashMap.put("Ralph Avenue", "Ralph Av");
        subwayHashMap.put("Rector Street", "Rector St");
        subwayHashMap.put("Rockaway Avenue", "Rockaway Av");
        subwayHashMap.put("Rockaway Boulevard", "Rockaway Blvd");
        subwayHashMap.put("Rockaway Park–Beach 116th Street", "Rockaway Park-Beach 116 St");
        subwayHashMap.put("Roosevelt Island", "Roosevelt Island");
        subwayHashMap.put("Saratoga Avenue", "Saratoga Av");
        subwayHashMap.put("Seneca Avenue", "Seneca Av");
        subwayHashMap.put("Sheepshead Bay", "Sheepshead Bay");
        subwayHashMap.put("Shepherd Avenue", "Shepherd Av");
        subwayHashMap.put("Simpson Street", "Simpson St");
        subwayHashMap.put("Smith–Ninth Streets", "Smith-9 Sts");
        subwayHashMap.put("South Ferry", "South Ferry");
        subwayHashMap.put("Spring Street", "Spring St");
        subwayHashMap.put("St. Lawrence Avenue", "St Lawrence Av");
        subwayHashMap.put("Steinway Street", "Steinway St");
        subwayHashMap.put("Sterling Street", "Sterling St");
        subwayHashMap.put("Sutphin Boulevard", "Sutphin Blvd");
        subwayHashMap.put("Sutphin Boulevard–Archer Avenue–JFK Airport", "Sutphin Blvd-Archer Av-JFK Airport");
        subwayHashMap.put("Sutter Avenue", "Sutter Av");
        subwayHashMap.put("Sutter Avenue–Rutland Road", "Sutter Av-Rutland Rd");
        subwayHashMap.put("Times Square–42nd Street", "Times Sq-42 St");
        subwayHashMap.put("Tremont Avenue", "Tremont Av");
        subwayHashMap.put("Union Street", "Union St");
        subwayHashMap.put("Utica Avenue", "Utica Av");
        subwayHashMap.put("Van Cortlandt Park–242nd Street", "Van Cortlandt Park-242 St");
        subwayHashMap.put("Van Siclen Avenue", "Van Siclen Av");
        subwayHashMap.put("Vernon Boulevard–Jackson Avenue", "Vernon Blvd-Jackson Av");
        subwayHashMap.put("West Fourth Street–Washington Square", "W 4 St-Wash Sq");
        subwayHashMap.put("West Eighth Street–New York Aquarium", "W 8 St-NY Aquarium");
        subwayHashMap.put("Wakefield–241st Street", "Wakefield-241 St");
        subwayHashMap.put("Wall Street", "Wall St");
        subwayHashMap.put("West Farms Square–East Tremont Avenue", "West Farms Sq-E Tremont Av");
        subwayHashMap.put("Westchester Square–East Tremont Avenue", "Westchester Sq-E Tremont Av");
        subwayHashMap.put("Whitehall Street–South Ferry", "Whitehall St-South Ferry");
        subwayHashMap.put("Whitlock Avenue", "Whitlock Av");
        subwayHashMap.put("Wilson Avenue", "Wilson Av");
        subwayHashMap.put("Winthrop Street", "Winthrop St");
        subwayHashMap.put("Woodhaven Boulevard", "Woodhaven Blvd");
        subwayHashMap.put("Woodlawn", "Woodlawn");
        subwayHashMap.put("World Trade Center", "World Trade Center");
        subwayHashMap.put("WTC Cortlandt", "WTC Cortlandt");
        subwayHashMap.put("York Street", "York St");
        subwayHashMap.put("Zerega Avenue", "Zerega Av");
        return subwayHashMap;
    }
}
